### ISSUE TITLE
Unable to install dmc2gym

### ISSUE THREAD

**Issue by darshitajain** [denisyarats/dmc2gym#13]
Thank you for open sourcing dmc2gym. I have been using dmc2gym since last year, but after yesterday I am unable to install dmc2gym using the mentioned installation command- 
pip install git+git://github.com/denisyarats/dmc2gym.git

It is showing the error-
![error](https://user-images.githubusercontent.com/19747895/158557984-f4c87889-b2e9-4579-b0ae-ef68d3b182a0.png)

I checked the mentioned link in the error message and found that Github has disabled support for unencrypted Git protocol (git://). What is the alternative way to install dmc2gym?

Request your help in this matter @denisyarats @bamos

**Comment by robinyu2021** [comment]
I met the same issue as well.

**Comment by mazpie** [comment]
Try with this command:

`pip install git+https://github.com/denisyarats/dmc2gym.git`

**Comment by darshitajain** [comment]
@mazpie Thank you. It helped.

**Comment by darshitajain** [comment]
@mazpie Thank you. It helped

> Try with this command:
> 
> `pip install git+https://github.com/denisyarats/dmc2gym.git`
