### ISSUE TITLE
dm-control OpenGL display error

### ISSUE THREAD

**Issue by episodeyang** [denisyarats/dmc2gym#4]
Hey Denis, thanks for this wrapper and congrats on your SAC_AE paper!

people have been running into a dm-control error when calling `from dm_control import mujoco` from within `dmc2gym`. 

You can see the error message here: https://github.com/deepmind/dm_control/issues/123#issuecomment-570456804

Will post here if I find a solution.

**Comment by episodeyang** [comment]
The issue is upstream, due to dm_control backend not configured correctly. 

For completeness here is the solution:

For those who are using a headless linux box without X-display,  use this:

```bash
      export MUJOCO_GL=osmesa
      export MJLIB_PATH=$HOME/.mujoco/mujoco200/bin/libmujoco200.so
      export MJKEY_PATH=$HOME/.mujoco/mujoco200/mjkey.txt
      export LD_LIBRARY_PATH=$HOME/.mujoco/mujoco200/bin:$LD_LIBRARY_PATH
      export MUJOCO_PY_MJPRO_PATH=$HOME/.mujoco/mujoco200/
      export MUJOCO_PY_MJKEY_PATH=$HOME/.mujoco/mujoco200/mjkey.txt
```

on Mac OSX, use the `glfw` backend instead: Notice that the `MJLIB_PATH` is changed to use `.dylib` postfix for `darwin`.

```bash
      export MUJOCO_GL=glfw
      export MJLIB_PATH=$HOME/.mujoco/mujoco200/bin/libmujoco200.dylib
      export MJKEY_PATH=$HOME/.mujoco/mujoco200/mjkey.txt
      export LD_LIBRARY_PATH=$HOME/.mujoco/mujoco200/bin:$LD_LIBRARY_PATH
      export MUJOCO_PY_MJPRO_PATH=$HOME/.mujoco/mujoco200/
      export MUJOCO_PY_MJKEY_PATH=$HOME/.mujoco/mujoco200/mjkey.txt
```

**Comment by denisyarats** [comment]
@episodeyang On Ubuntu, I've been using the following configuration to be able to render:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/.mujoco/mujoco200/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/nvidia-opengl/
MUJOCO_GL=egl
```
